export const actionTypes = {
  GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART_SINGLE_ITEM: "REMOVE_FROM_CART_SINGLE_ITEM",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
};
