export const actionTypes = {
  GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_SINGLE_ITEM_FROM_CART: "REMOVE_SINGLE_ITEM_FROM_CART",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
};
